<div class="wrap about-wrap">
	<h1>Thanks for Using Pricetable WP</h1>
	<div class="about-text">
		I hope you enjoy using it, as much as I enjoyed creating it.
		Your support means a lot!
	</div>
	<div class="pricetable-wp-badge">
		<div class="icon"></div>
		<h3>Pricetable WP Plugin v<?php print $info['Version'] ?></h3>
	</div>
	

	<p>
		If you need help with the plugin, give our <a href="#">pricetable WP documentation</a> a read.<br>
		If you ever get really stuck, then our free <a href="#">support forums</a> are a great place to get answers to your questions.
	</p>
</div> 